# Generated by Django 3.0.7 on 2020-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='answer',
            name='assignmentname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='staffname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='regno',
            field=models.CharField(max_length=20),
        ),
    ]
