# Generated by Django 3.1.4 on 2020-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20201216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
