# Generated by Django 3.1.4 on 2020-12-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='assignmentname',
        ),
        migrations.AddField(
            model_name='document',
            name='regno',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='staffname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
